### ISSUE TITLE
Parallel process boundary bug

### ISSUE THREAD

**Issue by thomasgibson** [firedrakeproject/gusto#109]
I have been running a shallow water simulation (Williamson test case 5) on Imperial's cluster and noticed some strange rough edges appearing when viewing the solution. Such as this (velocity field, 16 core job with sphere refinement level 6): 
![rough_spots](https://user-images.githubusercontent.com/14180421/26889607-a3d9436e-4ba6-11e7-958b-18711f232e98.png)

Tightening the projection tolerances in the initial condition, as well as in advection time stepping scheme for the velocity (theta method) helps, but it does not completely fix the issue. The pictures here are from a simulation with a tightened tolerance of `1e-12`.

It happens at the process boundaries, pictured here:
![process_boundary](https://user-images.githubusercontent.com/14180421/26889729-fc052eea-4ba6-11e7-9d97-40956ad2cd5c.png)

The magnitude of the anomalies seem significantly larger. I have tried using the branch https://github.com/firedrakeproject/firedrake/tree/bigger-halo-facet-integrals, but it doesn't fix the problem. This issue does not appear in serial runs.

**Comment by miklos1** [comment]
Did you run `make` in firedrake after switching branches?

**Comment by thomasgibson** [comment]
No I did not. I just ran `make clean` and `make`. The problem went away. Thanks for reminding me! My mistake. I'll go ahead and close this issue.
