### ISSUE TITLE
NoForcing

### ISSUE THREAD

**Issue by tommbendall** [firedrakeproject/gusto#132]
At the moment I think the `NoForcing` method won't work as there is no `pressure_gradient_term` defined, which should be as it is an abstract method.

**Comment by jshipton** [comment]
Thanks for pointing this out Tom. Do you still use NoForcing or does the AdvectionTimestepper do everything you need? At the moment, I can't think of a use for NoForcing so am tempted to fix this by just removing it - what do you think?

**Comment by tommbendall** [comment]
No I don't think I'd need to use it either! Removing it makes sense to me.
