### ISSUE TITLE
Gusto parameters should use UFL Constant

### ISSUE THREAD

**Issue by thomasgibson** [firedrakeproject/gusto#159]
Logging this issue here for now. Gusto parameters for thermodynamic constants and time-stepping parameters should really be using `ufl.Constant`. This causes forms to symbolically be recompiled, which is very noticeable when using Slate expressions. This should be a really easy fix.

**Comment by thomasgibson** [comment]
I started a branch https://github.com/firedrakeproject/gusto/tree/ufl-constant which replaces constants in the linear solvers with `ufl.Constant`. Perhaps this is all that's necessary? So changing the time-step `dt` shouldn't cause forms to be recompiled.

**Comment by jshipton** [comment]
Hi Thomas,


I thought it might be possible to have these parameters be ufl Constants everywhere if we did the right thing in the configuration.py file. That is:


1) make the default values Constant

2) in the __setattr__ method we could check to see if the named variable is a Constant and if it is, use assign.


I haven't tried this so not sure if it'll work - or if it is a good idea!

________________________________

**Comment by tommbendall** [comment]
Closing as now that FML is on the main branch this has been fixed
