### ISSUE TITLE
Hybrid solver failing on unsaturated bubble test

### ISSUE THREAD

**Issue by tommbendall** [firedrakeproject/gusto#169]
I've noticed that the hybridized compressible solver fails on my new unsaturated bubble test (the one featuring rain), whilst the old compressible solver seems to work.

With the hybrid solver it looks like gravity waves end up propagating and amplifying themselves, until at some point the CFL limit is breached and the model can no longer converge.

**Comment by thomasgibson** [comment]
Can you remind me: does the hybrid solver work using the "old style" advection schemes?

**Comment by tommbendall** [comment]
I am satisfied that this has been solved by PRs 191 and 194
