### ISSUE TITLE
Duplicated code for doing nodal averages

### ISSUE THREAD

**Issue by thomasgibson** [firedrakeproject/gusto#176]
This is just a comment that we should probably think about making the "averaging" operator, i.e. stuff with this piece of code:
```c
for (int i=0; i<%d; ++i) {
    for (int j=0; j<%d; ++j) {
        vec_out[i][j] += vec_in[i][j]/w[i][j];
    }
}
```
globally available. This bit of code it used whenever one transfers between a DG and CG space (or broken HDiv to HDiv). At the moment, it's duplicated in multiple locations within Gusto as a `par_loop`. Therefore, I think it's time to think about writing a single object performing the averaging that can be imported and used in Gusto.

We can discuss what the best way to do this is here. It's not super urgent, but something to think about!

**Comment by tommbendall** [comment]
I think such a piece of code might already exist! I think that the `Averager` operator in `recovery.py` does what you need?

**Comment by thomasgibson** [comment]
Oh, you're right! Totally forgot about that. I will submit a PR fixing the duplication.
