### ISSUE TITLE
NetCDF output fails on Archer

### ISSUE THREAD

**Issue by jshipton** [firedrakeproject/gusto#181]
It is conjectured that this is because some processes attempt to write to the .nc file before it is created.

**Comment by jshipton** [comment]
@dacreman it would be great if you could let us know the error here...

**Comment by jshipton** [comment]
OK, I've pushed a change with a barrier after the creation of the files... @P-Burns is going to try and test it...

**Comment by wence-** [comment]
Are all the netCDF4 things being linked against the right versions of stuff?

**Comment by dacreman** [comment]
I should add this this is an intermittent failure which is why I suspect a race condition is to blame.

**Comment by wence-** [comment]
Ah, OK.

**Comment by dacreman** [comment]
Fix proposed:  #182
