### ISSUE TITLE
R_d + cv = cp

### ISSUE THREAD

**Issue by gwimmer** [firedrakeproject/gusto#186]
The gas constant and specific heat at constant volume and pressure respectively currently don't quite add up in CompressibleParameters. I'd say we keep R_d=287. and cp=1004.5 as they are, and redefine cv as cv=cp - R_d=717.5.

(This makes a difference in the energy conserving Hamiltonian setup, since 
H = kin. energy + pot energy + cv rho theta pi,
leading to 
dH/dtheta = cp rho pi 
only if 
R_d + cv = cp).

**Comment by tommbendall** [comment]
Closing as this has been fixed by #257 -- thanks for pointing this out!
