### ISSUE TITLE
mkdir having problems in parallel

### ISSUE THREAD

**Issue by tommbendall** [firedrakeproject/gusto#190]
We think the new mkdir is causing problems in parallel, @thomasgibson has done a brief fix with this commit: d65cb822c1e1778ec09e73539f314f6bcb846ede on `solver-refactor` branch.

I'm just making a note of this so I remember - I'll file a pull request for this tomorrow morning!

**Comment by jshipton** [comment]
Yikes! We should have a parallel test...

**Comment by tommbendall** [comment]
In `Jenkinsfile` the command to execute the tests is `python -m pytest -n 4 -v tests`. I'd have thought this was ensuring the tests in parallel but apparently not...?

**Comment by thomasgibson** [comment]
Is it missing `mpiexec -n 4...`?

**Comment by thomasgibson** [comment]
This has already been fixed I believe (in #191)
