### ISSUE TITLE
Logger is completely untested

### ISSUE THREAD

**Issue by jshipton** [firedrakeproject/gusto#192]
Does anyone know if there is a straightforward way of testing the logging output? Do we want to do this?

**Comment by dham** [comment]
What do you want to test? It's probably possible to redirect the output to a file somewhere and check the contents, but I'm not quite sure what it would achieve.

**Comment by jshipton** [comment]
I spotted some bugs various places where warnings should have been logged (e.g. line 112 of linear_solvers.py - this is fixed now but it used to try to write to `state.logger` rather than importing `logger` from `gusto.configuration`). The bugs were not noticed because people currently using this code know what it's capable (or not capable!) of. I thought maybe we should have a test that tries to trigger these warnings and checks for them but that involves checking the logger output which seems messy.

I had a quick google and found this:
https://testfixtures.readthedocs.io/en/latest/logging.html
and this:
https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertLogs

but it wasn't sure which was best or if either were worth bothering with...

**Comment by jshipton** [comment]
No longer considered an issue.
