### ISSUE TITLE
dcmip_3-1_triangle_bdfm1 needs completing.

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/gusto#2]

**Comment by colinjcotter** [comment]
This is an example in examples/ showing dcmip 3-1 with triangular BDFM1. It also acts as a blueprint for how dcore is to be used.

**Comment by tommbendall** [comment]
We've made a new issue (#254) to specially cover creating the BDFM family -- hopefully that covers this issue!

**Comment by colinjcotter** [comment]
Thanks! I'm also much less obsessed with BDFM1 these days, BDM spaces on triangles are the default these days.
