### ISSUE TITLE
h_mountain test case often failing on Jenkins

### ISSUE THREAD

**Issue by tommbendall** [firedrakeproject/gusto#208]
We frequently see the `h_mountain` test case fail the test cases on Jenkins. It doesn't seem to consistently fail and I cannot yet reproduce it on another machine.

**Comment by thomasgibson** [comment]
Yeah don't worry, we know. I will try to diagnose it, but this is a particularly nasty/tricky bug. I'll update here if I find anything.

**Comment by tommbendall** [comment]
This is no longer a problem so this issue can be closed
