### ISSUE TITLE
Compressible hydrostatic balance not converging for higher order on 3D sphere

### ISSUE THREAD

**Issue by tommbendall** [firedrakeproject/gusto#223]
When running `compressible_hydrostatic_balance` with `solve_for_rho=True`, the  `rhosolver` does not converge for the higher order elements when the domain is an extruded `CubedSphereMesh`.

However the linear problem computed by the `PiSolver` does converge -- meaning that a `rho` close to discrete hydrostatic balance can still be computed by interpolating `theta` and `pi`.

There does not seem to be a problem for lower order elements or for extrusions of a `RectangleMesh`.

**Comment by jshipton** [comment]
This does not seem to be the case currently - the DCMIP example runs.
