### ISSUE TITLE
Update all doc strings and add clear documentation

### ISSUE THREAD

**Issue by tommbendall** [firedrakeproject/gusto#281]
We need to make sure all that documentation is up-to-date and that doc strings are formatted correctly.

When we tackle this we can make a checklist to go through it incrementally...

**Comment by jshipton** [comment]
This should take place in the `FML_website` branch, or in a branch off of it, since I have started fixing the doctoring formatting there.

**Comment by tommbendall** [comment]
I will do the doc strings for:

- [ ] `kernels.py`
- [ ] `limiters.py`
- [ ] `linear_solvers.py`
- [ ] `physics.py`
- [ ] `preconditioners.py`
- [ ] `recovery.py`
- [ ] `state.py`
- [ ] `thermodynamics.py`
- [ ] `time_discretisation.py`
- [ ] `transport_forms.py`

**Comment by tommbendall** [comment]
Closing as this has been completed for now!
