### ISSUE TITLE
Rename a couple of time steppers / discretisations

### ISSUE THREAD

**Issue by tommbendall** [firedrakeproject/gusto#283]
I think we should rename `CrankNicolson` to `SemiImplicitQuasiNewton`. I also wonder if we should rename `ThetaMethod` to `TrapezoidalRule` or something similar.

**Comment by jshipton** [comment]
I agree to both!

**Comment by atb1995** [comment]
First part has already done. I've had a look through some literature and think `ThetaMethod` should remain as it is, I can't seem to find a name for u^(n+1) = u^n + dt(alpha*F^(n+1) + (1-alpha)*F^n), other than "General Two-Step Method".. 

I think `ImplicitMidpoint` on the other hand could be called `CrankNicholson` or `TrapeziodalMethod`, as it would only be the implicit midpoint rule if the method is linear..
