### ISSUE TITLE
Add jupyter-notebooks as examples

### ISSUE THREAD

**Issue by tommbendall** [firedrakeproject/gusto#284]
We need to add some jupyter-notebooks as examples.

**Comment by jshipton** [comment]
we can test these run using the `--nbval-lax` option, which will only check if they run and not check the output - see: https://nbval.readthedocs.io/en/latest/

**Comment by jshipton** [comment]
These are in #294 - they need updating, but this will be a regular thing so we no longer need this issue to remind us!
