### ISSUE TITLE
Log statements are appearing twice

### ISSUE THREAD

**Issue by tommbendall** [firedrakeproject/gusto#387]
There is something odd going on with the logger, I keep on seeing every log statement twice, e.g.:

```
gusto:INFO at start of timestep, t=0.0, dt=1.0
INFO:gusto:at start of timestep, t=0.0, dt=1.0
```

This is confusing and needs fixing.

**Comment by jshipton** [comment]
@tommbendall how do I make this happen? it all looks ok to me...

**Comment by tommbendall** [comment]
Closing as this seems to be fixed by updating firedrake
