### ISSUE TITLE
Parallel test failure (on CI)

### ISSUE THREAD

**Issue by JDBetteridge** [firedrakeproject/gusto#433]
One of the tests is timing out when run in parallel:
https://github.com/firedrakeproject/gusto/actions/runs/6014541349/job/16314464111
```
FAILED examples/test_examples_run.py::test_example_runs_parallel[unsaturated_bubble.py]
```

I can't reproduce the error locally, but there appears to be a deadlock (or potentially more than one).

This is currently holding up #417, and potentially points towards a bigger issue.

I have attached the logfiles from the CI run.
[log-files.zip](https://github.com/firedrakeproject/gusto/files/12477341/log-files.zip)

**Comment by tommbendall** [comment]
This has now been understood and addressed -- we were actually hitting the time out because the compilation (particularly of steps in the hybridized solver) was very slow. By increasing the time limit and speeding up the compilation by changing the compiler flags, Jack has now addressed this.
