### ISSUE TITLE
Can't run any .py in /examples/

### ISSUE THREAD

**Issue by adominious** [firedrakeproject/gusto#455]
Please help, I can't run anything in the examples dir. Upon some debugging, it is released to the line import from gusto * (commenting out stops error). This is what I get:

Caught signal number 11 SEGV: Segmentation Violation, probably memory access out of range

please help thanks.

**Comment by tommbendall** [comment]
Hi, thanks for trying to use Gusto!

The first step is to check if you have a working Firedrake installation and if you are working in the Firedrake virtual environment?

There are instructions on how to check this here: https://www.firedrakeproject.org/download.html#testing-the-installation

Did you install Gusto through a standard Firedrake installation?

**Comment by adominious** [comment]
Hi there,

Yes I followed the instructions presented on the Gusto download page. Running ‘make test’ was successful.

Adam Hayes
UKRI CDT in Accountable, Responsible and Transparent AI
Department of Computer Science, Mathematics, Social & Policy Sciences, Engineering
University of Bath



[signatureImage]   [signatureImage]    [signatureImage]
________________________________

**Comment by adominious** [comment]
I’m assuming it’s the Gusto version as I cd into gusto/

**Comment by tommbendall** [comment]
OK great, that's the first hurdle! So to clarify, you can successfully run the Firedrake tests?

Do you get the same failure when running the Gusto tests? To do this, run `make test` in your `<path_to_firedrake>/src/gusto` directory.

Otherwise, my current hunch is that your error is related to the PETSc installation on your computer (a quick google of the error message leads to PETSc results). From your issue #454, I'm guessing that you might not have installed PETSc through Firedrake?

**Comment by adominious** [comment]
This is right. I had an existing version on PETSc. Unfortunately I cannot install gusto without pre-installing PETSc, I always get an error during the Gusto installation.

**Comment by jshipton** [comment]
What is the output of `make test` and how long does it take? I'm puzzled by how that can be working.

**Comment by adominious** [comment]
My apologies, `make test` no longer seems to be successful. It has been in the past but something must have caused this to error. I now receive the following:

```
ImportError while loading conftest '/home/adamh/firedrake/src/gusto/integration-tests/conftest.py'.
integration-tests/conftest.py:5: in <module>
    from firedrake import (IcosahedralSphereMesh, PeriodicIntervalMesh,
E   ModuleNotFoundError: No module named 'firedrake'

```

**Comment by jshipton** [comment]
Have you definitely activated your Firedrake virtual environment?

**Comment by adominious** [comment]
My mistake, upon activating the virtual environment. I have a new error:

```
ImportError while loading conftest '/home/adamh/firedrake/src/gusto/integration-tests/conftest.py'.
integration-tests/conftest.py:5: in <module>
    from firedrake import (IcosahedralSphereMesh, PeriodicIntervalMesh,
../firedrake/firedrake/__init__.py:69: in <module>
    from pyop2 import op2                        # noqa: F401
../PyOP2/pyop2/__init__.py:4: in <module>
    from pyop2.op2 import *  # noqa
../PyOP2/pyop2/op2.py:40: in <module>
    from pyop2.mpi import MPI, COMM_WORLD, collective
../PyOP2/pyop2/mpi.py:65: in <module>
    COMM_WORLD = PETSc.COMM_WORLD.tompi4py().Dup()
petsc4py/PETSc/Comm.pyx:166: in petsc4py.PETSc.Comm.tompi4py
    ???
petsc4py/PETSc/petscmpi.pxi:62: in petsc4py.PETSc.mpi4py_Comm_New
    ???
mpi4py/MPI/CAPI.pxi:111: in mpi4py.MPI.PyMPIComm_New
    ???
E   mpi4py.MPI.Exception: Invalid communicator, error stack:
E   internal_Comm_test_inter(78): MPI_Comm_test_inter(comm=0x284e9780, flag=0x7ffec2112cf4) failed
E   internal_Comm_test_inter(42): Invalid communicator
```

**Comment by jshipton** [comment]
Are you able to run the Firedrake `make test`?

**Comment by adominious** [comment]
How would I go about doing this (I am very much so a newbie with anything Linux)

**Comment by tommbendall** [comment]
You can go to the firedrake package directory and then run some of the tests from there:
```
cd <path_to_firedrake>/src/firedrake
make test
```

**Comment by adominious** [comment]
Thank you. I receive quite a large error. But it ends with the following:

`Key Error: 'honour_petsc_dir'`

**Comment by jshipton** [comment]
OK, this seems to also be related to PETSc and should probably be discussed on the Firedrake page as there are more people with experience there.

It sounds like you are trying to use a PETSc that you have already installed, but when you installed Firedrake you didn't tell it where to find that PETSc...

**Comment by adominious** [comment]
okay, thank you for your help, I will raise it with them
