### ISSUE TITLE
Improvements to embedded DG

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/gusto#49]
A few improvements:

(1) The embedded DG __init__ method should build the broken element function space
(2) A Projector should be used to speed this up.

**Comment by wence-** [comment]
Both of these were addressed in #51.  Which is now merged.  Although I note in passing that the `BrokenElement` approach for building the DG space will not work automagically in all cases.  If you pass a `VectorFunctionSpace` in, for example, it will fail.

**Comment by jshipton** [comment]
Yes, I'm just adding in testing and making an fail for the vector case.

________________________________
