### ISSUE TITLE
Examples bitrot

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/gusto#53]
The examples are good ways of showing longer-running more "realistic" usages.  However, they are currently completely untested as part of the build system.  For example, on current master, neither the `dense_bubble.py` nor the `rising_bubble.py` examples run.

How might one test this?  The examples might have a "test" option which runs them for one timestep on a tiny mesh (to at least ensure they run).  We can hook this up automagically like we do for the firedrake documented demos.

**Comment by jshipton** [comment]
Yes, this would be wonderful - in fact, I asked about it a couple of week ago as I kept breaking Colin's examples! It's good to have you back Lawrence!

________________________________

**Comment by jshipton** [comment]
Just coming back to this @wence as I'm restructuring part of the code which means I need to fix up some examples - some of which I think don't run on current master so it'd be nice to know which ones I've broken and which are broken already. Where can I find out how to add this "test" option you mention?

**Comment by wence-** [comment]
So what we do in firedrake is this (in `tests/demos/test_demos_run.py`)

```python
import pytest
from os.path import abspath, basename, dirname, join, splitext
import os
import subprocess
import glob
import sys


cwd = abspath(dirname(__file__))
demo_dir = join(cwd, "..", "..", "demos")
pylit = join(cwd, "..", "..", "pylit", "pylit.py")


# Discover the demo files by globbing the demo directory
@pytest.fixture(params=glob.glob("%s/*/*.py.rst" % demo_dir),
                ids=lambda x: basename(x))
def rst_file(request):
    return abspath(request.param)


@pytest.fixture
def py_file(rst_file, tmpdir, monkeypatch):
    # Change to the temporary directory (monkeypatch ensures that this
    # is undone when the fixture usage disappears)
    monkeypatch.chdir(tmpdir)

    # Check if we need to generate any meshes
    geos = glob.glob("%s/*.geo" % dirname(rst_file))
    for geo in geos:
        name = "%s.msh" % splitext(basename(geo))[0]
        try:
            subprocess.check_call(["gmsh", geo, "-3", "-o", str(tmpdir.join(name))])
        except (subprocess.CalledProcessError, OSError):
            # Skip if unable to make mesh
            pytest.skip("Unable to generate mesh file, skipping test")

    # Get the name of the python file that pylit will make
    name = splitext(basename(rst_file))[0]
    output = str(tmpdir.join(name))
    # Convert rst demo to runnable python file
    subprocess.check_call([pylit, rst_file, output])
    return output


def test_demo_runs(py_file):
    subprocess.check_call([sys.executable, py_file])
```

Which enumerates all the demos, sets them up to run and then runs them in a subprocess.

**Comment by wence-** [comment]
You could do something like:

```python
import pytest
from os.path import abspath, basename, dirname, join
import subprocess
import glob
import sys


cwd = abspath(dirname(__file__))
examples_dir = join(cwd, "..", "examples")


@pytest.fixture(params=glob.glob("%s/*.py" % examples_dir),
                ids=lambda x: basename(x))
def example_file(request):
    return abspath(request.param)


def test_example_runs(example_file, tmpdir, monkeypatch):
    # This ensures that the test writes output in a temporary
    # directory, rather than where pytest was run from.
    monkeypatch.chdir(tmpdir)
    subprocess.check_call([sys.executable, example_file])
```

Now, the tests take quite a long time to run.  So if you want to run them fast (just to check that everything still does a timestep) you'll need to rework them so that you can specify a small "test" version.

**Comment by jshipton** [comment]
Thanks Lawrence. I have got this to work running the examples files as they are. How do you recommend reworking the examples files to specify a small test version? I found this page that suggests you can detect if you are running from py.test:


http://doc.pytest.org/en/latest/example/simple.html


...but it also says this is not generally recommended so I thought I'd get your approval!

________________________________

**Comment by wence-** [comment]
I would instead add an extra command line flag that you inspect when running the test.  Then you can do:
```python
subprocess.check_call([sys.executable, example_file, "--running-tests"])
```

And then your example file checks if `sys.argv` contains `--running-tests` and does the appropriate thing.

Note that the suggestion in the pytest  docs won't work, because you're executing the test in a subprocess, so it doesn't see the same modules that pytest does.

**Comment by jshipton** [comment]
That works brilliantly - thank you!

________________________________

**Comment by jshipton** [comment]
Yikes! See what you mean about the number of broken examples!

________________________________
