### ISSUE TITLE
Rotation should be included in the linear solver

### ISSUE THREAD

**Issue by tommbendall** [firedrakeproject/gusto#532]
The Coriolis force is not included in any of our linear solvers, but it is included in GungHo's. I am optimistic that this may explain the instability of our 2x2 formulations, which I've only seen in 3D models including rotation.

**Comment by colinjcotter** [comment]
Oh! Either that's a regression or I had forgotten about it.

**Comment by tommbendall** [comment]
Closing as this was addressed by #539
