### ISSUE TITLE
printing

### ISSUE THREAD

**Issue by jshipton** [firedrakeproject/gusto#72]
Make printing more friendly in parallel and think about whether we need any other print statements  to help new users.

**Comment by jshipton** [comment]
I'm already using the Firedrake warning function - should I be using the Firedrake logging module to print out user friendly logging statements?

**Comment by jshipton** [comment]
thoughts? @wence- @dham

**Comment by wence-** [comment]
So what you should do is make a `gusto` logger, and then set it to only print on rank 0.

```python
import logging

logger = logget.getLogger("gusto")

handler = logging.StreamHandler()
handler.setFormatter(logging.Formatter(fmt="%(name)s:%(levelname)s %(message)s"))
if COMM_WORLD.rank == 0:
    logger.addHandler(handler)
else:
    logger.addHandler(logging.NullHandler())
```

**Comment by jshipton** [comment]
Thank you!
