### ISSUE TITLE
Potential moving mesh issues

### ISSUE THREAD

**Issue by jshipton** [firedrakeproject/gusto#80]
This is a list of things that could potentially go wrong with moving meshes with Gusto. Please add anything you spot!

1) constant_jacobian is assumed true - needs to be false in all Gusto solvers if the mesh is moving. There are some places where this is quite hidden away, e.g. the Projector defined for embedded DG advection methods

2) cached properties  in advection schemes probably need to become mere properties.

**Comment by colinjcotter** [comment]
OK, we probably need a self.constant_jacobian which we use in all solvers and projectors

**Comment by jshipton** [comment]
Not currently possible to pass constant_jacobian=False into Projector. This will need fixing for embedded DG advection on a moving mesh and also for the NoAdvection projecting in MovingMeshAdvectionManager

**Comment by jshipton** [comment]
Comments moved to discussion #264
