### ISSUE TITLE
firedrake-install is broken on travis

### ISSUE THREAD

**Issue by jshipton** [firedrakeproject/gusto#81]
@wence- all Gusto testing is currently failing on Travis due to a problem with Eigen in the Firedrake install. See, for example: https://travis-ci.org/firedrakeproject/gusto/builds/196555006

**Comment by wence-** [comment]
Ugh, looks like the travis containers are running 12.04, in which the cmake install is so old that eigen doesn't build with it...

PETSc can `--download-cmake`, seeing if that fixes the problem...

**Comment by dorugeber** [comment]
Can you go to Trusty (14.04)?  https://docs.travis-ci.com/user/trusty-ci-environment/

**Comment by wence-** [comment]
Probably, but that is allegedly still in beta.  My workaround is to get petsc to build cmake, then it uses that cmake which can build eigen.

**Comment by wence-** [comment]
I fixed the build, but now the gusto tests butt up close to the travis 50 minute timeout.  I guess we hadn't migrated to the drone setup because previously it wasn't an issue.  Can do that now.
