### ISSUE TITLE
fix advection for H-div elements on the sphere

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/gusto#85]
Advective form of transport for H-div elements has contributions from u.n but these aren't needed, and also are probably wrong at the moment.

**Comment by tommbendall** [comment]
I think the `vector_manifold` term in the DG upwind transport is the correct thing to do here. There is a question as to whether this should be configurable by the user -- we are  shortly going to make an issue or design discussion for how to configure the transport options so I will make sure to include a note about this in that issue / discussion.
