### ISSUE TITLE
detecting if element is DG/CG

### ISSUE THREAD

**Issue by jshipton** [firedrakeproject/gusto#86]
Currently broken and maybe not the best way of doing it anyway - add a user option to interface instead?

**Comment by thomasgibson** [comment]
Couldn't this be determined by examining `V.ufl_element().sobolev_space()`, where `V` is your function space?

**Comment by thomasgibson** [comment]
Can be done by checking `V.ufl_element().sobolev_space().name`

**Comment by jshipton** [comment]
@thomasgibson that looks like it should work - thanks! Is there a way of figuring out in which direction a space is discontinuous? i.e. for the theta space?

**Comment by thomasgibson** [comment]
Yes! So if `V` is your theta space, then `sobolev_space = V.ufl_element().sobolev_space()` gives you a `DirectionalSobolevSpace`. In the case of `V`, it will be `DirectionalH`. You can then index the space by the spatial indices (0, 1, or 2 (if 3d)). And you will get that `sobolev_space[i].name` is `"H1"` or `"L2"`

**Comment by jshipton** [comment]
Ah, that's what the H means! Cool - thanks!

**Comment by jshipton** [comment]
Hm, what if I have a `VectorFunctionSpace`? I'm getting: AttributeError: 'VectorElement' object has no attribute 'sobolev_space'

**Comment by thomasgibson** [comment]
Oh I see. Might need fixing in UFL later. But for the moment, you can ask a `VectorElement` for its `sub_elements`: `E._sub_elements` and that gives a list of the `FiniteElement` objects in the spatial directions. Each of those should have a sobolev space method

**Comment by jshipton** [comment]
How about `BrokenElement`?

**Comment by jshipton** [comment]
oh, of course, that's always DG but it'll need a separate check...

**Comment by jshipton** [comment]
This has been fixed.
