### ISSUE TITLE
don't use preonly for solver if CG in transport equation

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/gusto#91]
Transport equation sets preonly as default solver for advection but this is only suitable for DG.

**Comment by thomasgibson** [comment]
Can you confirm whether or not conjugate gradient + bjacobi/ILU is sufficient? This is being addressed in #111

**Comment by wence-** [comment]
It's fine, it's just a mass matrix.  If you care about reductions (I don't think you do), you could use cheby + ilu, but then you need eigenvalue bounds (can be explicitly calculated), but I don't think it's worth it.

**Comment by thomasgibson** [comment]
Fixed in #111
